In [25]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [26]:
# head()
# tail()
# missing value
# if misiing values present fill it
# data type   (int or float)  if object data available convert it to numeric data
# seperate input and output  x:input    y:output
df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [27]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [28]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [29]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [30]:
x=df.iloc[::-1].values            # x always in 2 diamensional data
x

array([[  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       ...,
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ]])

In [31]:
y=df.iloc[:,-1].values        # y always in 1 dimensional data
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [32]:
#training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
x_train

array([[  2.   , 127.   ,  58.   , ...,   1.6  ,  25.   ,   0.   ],
       [  1.   , 100.   ,  66.   , ...,   0.666,  26.   ,   0.   ],
       [  7.   , 168.   ,  88.   , ...,   0.787,  40.   ,   1.   ],
       ...,
       [ 14.   , 100.   ,  78.   , ...,   0.412,  46.   ,   1.   ],
       [ 13.   ,  76.   ,  60.   , ...,   0.18 ,  41.   ,   0.   ],
       [  1.   , 119.   ,  54.   , ...,   0.205,  24.   ,   0.   ]])

In [33]:
x_test

array([[  2.   ,  87.   ,   0.   , ...,   0.773,  25.   ,   0.   ],
       [  2.   , 120.   ,  76.   , ...,   0.215,  29.   ,   0.   ],
       [ 10.   , 108.   ,  66.   , ...,   0.272,  42.   ,   1.   ],
       ...,
       [ 10.   ,  94.   ,  72.   , ...,   0.595,  56.   ,   0.   ],
       [  3.   , 129.   ,  92.   , ...,   0.968,  32.   ,   1.   ],
       [ 13.   , 129.   ,   0.   , ...,   0.569,  44.   ,   1.   ]])

In [54]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [55]:
y_test

array([[2.00000000e+00, 8.70000000e+01, 1.02959230e-16, ...,
        7.73000000e-01, 2.50000000e+01, 5.41673059e-17],
       [2.00000000e+00, 1.20000000e+02, 7.60000000e+01, ...,
        2.15000000e-01, 2.90000000e+01, 5.41673059e-17],
       [1.00000000e+01, 1.08000000e+02, 6.60000000e+01, ...,
        2.72000000e-01, 4.20000000e+01, 1.00000000e+00],
       ...,
       [1.00000000e+01, 9.40000000e+01, 7.20000000e+01, ...,
        5.95000000e-01, 5.60000000e+01, 5.41673059e-17],
       [3.00000000e+00, 1.29000000e+02, 9.20000000e+01, ...,
        9.68000000e-01, 3.20000000e+01, 1.00000000e+00],
       [1.30000000e+01, 1.29000000e+02, 1.02959230e-16, ...,
        5.69000000e-01, 4.40000000e+01, 1.00000000e+00]])

In [56]:
#normalization
# 1.standard scaler
# 2.MinMax scaler


# 1. Standard Scaler

# z=(x-u)/s
# z= normalized chaitha output
# x=input
# u= mean of training data
# s=standard deviation
# Normalization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)   #z=(x-u)/s
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train


array([[-0.53001472,  0.22972848, -0.57062316, ...,  3.64169928,
        -0.69721676, -0.73394955],
       [-0.82835634, -0.60548548, -0.15251006, ...,  0.65303298,
        -0.6094312 , -0.73394955],
       [ 0.96169338,  1.49801635,  0.99730096, ...,  1.04021566,
         0.61956659,  1.36249146],
       ...,
       [ 3.05008473, -0.60548548,  0.47465959, ..., -0.15973066,
         1.14627993,  1.36249146],
       [ 2.75174311, -1.34789789, -0.46609489, ..., -0.90209745,
         0.70735215, -0.73394955],
       [-0.82835634, -0.01774232, -0.77967971, ..., -0.82210103,
        -0.78500231, -0.73394955]])

In [57]:
x_test

array([[ 2.00000000e+00,  8.70000000e+01, -5.91291965e-17, ...,
         7.73000000e-01,  2.50000000e+01, -3.96951249e-17],
       [ 2.00000000e+00,  1.20000000e+02,  7.60000000e+01, ...,
         2.15000000e-01,  2.90000000e+01, -3.96951249e-17],
       [ 1.00000000e+01,  1.08000000e+02,  6.60000000e+01, ...,
         2.72000000e-01,  4.20000000e+01,  1.00000000e+00],
       ...,
       [ 1.00000000e+01,  9.40000000e+01,  7.20000000e+01, ...,
         5.95000000e-01,  5.60000000e+01, -3.96951249e-17],
       [ 3.00000000e+00,  1.29000000e+02,  9.20000000e+01, ...,
         9.68000000e-01,  3.20000000e+01,  1.00000000e+00],
       [ 1.30000000e+01,  1.29000000e+02, -5.91291965e-17, ...,
         5.69000000e-01,  4.40000000e+01,  1.00000000e+00]])

In [58]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1])

In [59]:
y_test

array([[2.00000000e+00, 8.70000000e+01, 1.02959230e-16, ...,
        7.73000000e-01, 2.50000000e+01, 5.41673059e-17],
       [2.00000000e+00, 1.20000000e+02, 7.60000000e+01, ...,
        2.15000000e-01, 2.90000000e+01, 5.41673059e-17],
       [1.00000000e+01, 1.08000000e+02, 6.60000000e+01, ...,
        2.72000000e-01, 4.20000000e+01, 1.00000000e+00],
       ...,
       [1.00000000e+01, 9.40000000e+01, 7.20000000e+01, ...,
        5.95000000e-01, 5.60000000e+01, 5.41673059e-17],
       [3.00000000e+00, 1.29000000e+02, 9.20000000e+01, ...,
        9.68000000e-01, 3.20000000e+01, 1.00000000e+00],
       [1.30000000e+01, 1.29000000e+02, 1.02959230e-16, ...,
        5.69000000e-01, 4.40000000e+01, 1.00000000e+00]])