In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/Laptops.csv')
df

Unnamed: 0    Brand               Model Name          Processor  \
0             0       HP             15s-fq5007TU            Core i3   
1             1       HP             15s-fy5003TU            Core i3   
2             2    Apple         2020 Macbook Air                 M1   
3             3    Apple         2020 Macbook Air                 M1   
4             4    Apple         2020 Macbook Air                 M1   
..          ...      ...                      ...                ...   
832         832       HP                   255 G8  Ryzen 5 Hexa Core   
833         833     DELL            Inspiron 7430            Core i3   
834         834      MSI  Katana 17 B13UCXK-256IN            Core i7   
835         835  Infinix                     XL25            Core i5   
836         836       HP              13-BE0030AU  Ryzen 5 Hexa Core   

    Operating System Storage    RAM           Screen Size Touch_Screen  \
0    Windows 11 Home  512 GB   8 GB  39.62 cm (15.6 Inch)           No   
1    Windows 11 Home  512 GB   8 GB  39.62 cm (15.6 Inch)           No   
2     Mac OS Big Sur  256 GB   8 GB  33.78 cm (13.3 inch)           No   
3     Mac OS Big Sur  256 GB   8 GB  33.78 cm (13.3 inch)           No   
4     Mac OS Big Sur  256 GB   8 GB  33.78 cm (13.3 inch)           No   
..               ...     ...    ...                   ...          ...   
832  Windows 11 Home  512 GB   8 GB  39.62 cm (15.6 inch)           No   
833  Windows 11 Home    1 TB   8 GB    35.56 cm (14 inch)          Yes   
834  Windows 11 Home    4 TB  16 GB  43.94 cm (17.3 Inch)           No   
835  Windows 11 Home  512 GB   8 GB  39.62 cm (15.6 Inch)           No   
836  Windows 10 Home  512 GB  16 GB  33.78 cm (13.3 inch)           No   

       Price  
0    ₹38,990  
1    ₹37,990  
2    ₹70,990  
3    ₹70,990  
4    ₹70,990  
..       ...  
832  ₹42,990  
833  ₹60,490  
834  ₹88,990  
835  ₹37,990  
836  ₹70,500  

[837 rows x 10 columns]

In [12]:
df.head()

Unnamed: 0  Brand        Model Name Processor Operating System Storage  \
0           0     HP      15s-fq5007TU   Core i3  Windows 11 Home  512 GB   
1           1     HP      15s-fy5003TU   Core i3  Windows 11 Home  512 GB   
2           2  Apple  2020 Macbook Air        M1   Mac OS Big Sur  256 GB   
3           3  Apple  2020 Macbook Air        M1   Mac OS Big Sur  256 GB   
4           4  Apple  2020 Macbook Air        M1   Mac OS Big Sur  256 GB   

    RAM           Screen Size Touch_Screen    Price  
0  8 GB  39.62 cm (15.6 Inch)           No  ₹38,990  
1  8 GB  39.62 cm (15.6 Inch)           No  ₹37,990  
2  8 GB  33.78 cm (13.3 inch)           No  ₹70,990  
3  8 GB  33.78 cm (13.3 inch)           No  ₹70,990  
4  8 GB  33.78 cm (13.3 inch)           No  ₹70,990

In [13]:
df.tail()

Unnamed: 0    Brand               Model Name          Processor  \
832         832       HP                   255 G8  Ryzen 5 Hexa Core   
833         833     DELL            Inspiron 7430            Core i3   
834         834      MSI  Katana 17 B13UCXK-256IN            Core i7   
835         835  Infinix                     XL25            Core i5   
836         836       HP              13-BE0030AU  Ryzen 5 Hexa Core   

    Operating System Storage    RAM           Screen Size Touch_Screen  \
832  Windows 11 Home  512 GB   8 GB  39.62 cm (15.6 inch)           No   
833  Windows 11 Home    1 TB   8 GB    35.56 cm (14 inch)          Yes   
834  Windows 11 Home    4 TB  16 GB  43.94 cm (17.3 Inch)           No   
835  Windows 11 Home  512 GB   8 GB  39.62 cm (15.6 Inch)           No   
836  Windows 10 Home  512 GB  16 GB  33.78 cm (13.3 inch)           No   

       Price  
832  ₹42,990  
833  ₹60,490  
834  ₹88,990  
835  ₹37,990  
836  ₹70,500

In [14]:
df.isna().sum()

Unnamed: 0           0
Brand                0
Model Name           0
Processor            0
Operating System     0
Storage             12
RAM                  0
Screen Size          0
Touch_Screen         0
Price                0
dtype: int64

In [15]:
m=df['Storage'].mode()[0]
df['Storage'].fillna(m,inplace=True)
df.isna().sum()

Unnamed: 0          0
Brand               0
Model Name          0
Processor           0
Operating System    0
Storage             0
RAM                 0
Screen Size         0
Touch_Screen        0
Price               0
dtype: int64

In [16]:
df.dtypes

Unnamed: 0           int64
Brand               object
Model Name          object
Processor           object
Operating System    object
Storage             object
RAM                 object
Screen Size         object
Touch_Screen        object
Price               object
dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['Brand']=lb.fit_transform(df['Brand'])
df['Model Name']=lb.fit_transform(df['Model Name'])
df['Processor']=lb.fit_transform(df['Processor'])
df['Operating System']=lb.fit_transform(df['Operating System'])
df['Storage']=lb.fit_transform(df['Storage'])
df['RAM']=lb.fit_transform(df['RAM'])
df['Screen Size']=lb.fit_transform(df['Screen Size'])
df['Touch_Screen']=lb.fit_transform(df['Touch_Screen'])
df.dtypes

Unnamed: 0           int64
Brand                int64
Model Name           int64
Processor            int64
Operating System     int64
Storage              int64
RAM                  int64
Screen Size          int64
Touch_Screen         int64
Price               object
dtype: object

In [18]:
x=df.iloc[:,:-1]
x

Unnamed: 0  Brand  Model Name  Processor  Operating System  Storage  RAM  \
0             0      6          83          3                10        6    6   
1             1      6          89          3                10        6    6   
2             2      2         100          7                 2        3    6   
3             3      2         100          7                 2        3    6   
4             4      2         100          7                 2        3    6   
..          ...    ...         ...        ...               ...      ...  ...   
832         832      6         105         22                10        6    6   
833         833      4         216          3                10        0    6   
834         834     11         233          5                10        5    1   
835         835      7         362          4                10        6    6   
836         836      6           1         22                 8        6    1   

     Screen Size  Touch_Screen  
0             26             0  
1             26             0  
2              9             0  
3              9             0  
4              9             0  
..           ...           ...  
832           27             0  
833           17             1  
834           33             0  
835           26             0  
836            9             0  

[837 rows x 9 columns]

In [19]:
y=df.iloc[:,-1]
y

0      ₹38,990
1      ₹37,990
2      ₹70,990
3      ₹70,990
4      ₹70,990
        ...   
832    ₹42,990
833    ₹60,490
834    ₹88,990
835    ₹37,990
836    ₹70,500
Name: Price, Length: 837, dtype: object

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=2)
x_train

Unnamed: 0  Brand  Model Name  Processor  Operating System  Storage  RAM  \
178         178      4         208          3                10        6    6   
176         176      6          86          4                10        6    6   
267         267      6          86          4                10        6    6   
251         251      6          75          4                10        6    6   
58           58      0         321          3                10        2    6   
..          ...    ...         ...        ...               ...      ...  ...   
534         534      0         357          5                10        6    1   
584         584      6           4         22                10        6    1   
493         493      0         230         24                10        6    1   
527         527      6          76          4                10        6    1   
168         168      6          88          4                10        6    6   

     Screen Size  Touch_Screen  
178           36             0  
176           27             0  
267           27             0  
251           26             0  
58            27             0  
..           ...           ...  
534           27             0  
584           17             0  
493           26             0  
527           27             0  
168           26             0  

[585 rows x 9 columns]

In [22]:
x_test

Unnamed: 0  Brand  Model Name  Processor  Operating System  Storage  RAM  \
399         399      1         266         22                 8        0    6   
513         513      6          83          3                10        6    6   
436         436     17         128          4                10        6    1   
284         284      1         119          4                10        6    6   
67           67      6          86          4                10        6    6   
..          ...    ...         ...        ...               ...      ...  ...   
468         468      7         192          3                10        3    6   
792         792      6          88          4                10        6    6   
272         272      0         246         22                10        6    6   
382         382      9          14          3                10        6    6   
595         595      0         219          4                10        6    1   

     Screen Size  Touch_Screen  
399           26             0  
513           26             0  
436           17             0  
284           26             0  
67            27             0  
..           ...           ...  
468           17             0  
792           26             0  
272           26             0  
382           16             0  
595           16             0  

[252 rows x 9 columns]

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array(['₹1,47,743', '₹37,990', '₹16,990', '₹37,990', '₹49,990',
       '₹1,28,990', '₹89,990', '₹38,990', '₹53,990', '₹1,47,743',
       '₹37,990', '₹18,990', '₹29,800', '₹66,999', '₹1,37,999', '₹37,990',
       '₹53,990', '₹38,990', '₹38,990', '₹1,33,990', '₹38,990', '₹53,990',
       '₹46,990', '₹20,990', '₹36,607', '₹53,990', '₹1,47,743',
       '₹1,19,990', '₹2,20,579', '₹41,000', '₹38,990', '₹23,990',
       '₹54,990', '₹62,990', '₹37,990', '₹54,990', '₹37,990', '₹53,990',
       '₹3,70,890', '₹11,990', '₹27,990', '₹41,000', '₹1,62,990',
       '₹37,990', '₹37,990', '₹1,24,990', '₹23,990', '₹1,03,990',
       '₹53,990', '₹2,37,890', '₹77,990', '₹1,47,689', '₹26,890',
       '₹53,990', '₹32,990', '₹41,000', '₹26,890', '₹77,990', '₹53,990',
       '₹38,990', '₹37,990', '₹1,04,990', '₹37,990', '₹53,990',
       '₹2,20,579', '₹35,855', '₹66,999', '₹38,990', '₹2,20,579',
       '₹54,990', '₹53,990', '₹77,990', '₹20,990', '₹20,990', '₹54,990',
       '₹77,990', '₹1,03,990', '₹37,990', '

In [26]:
y_test

399    ₹62,990
513    ₹38,990
436    ₹56,999
284    ₹62,990
67     ₹53,990
        ...   
468    ₹37,999
792    ₹49,990
272    ₹50,990
382    ₹34,990
595    ₹82,990
Name: Price, Length: 252, dtype: object

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
score=accuracy_score(y_test,y_pred)
score

0.07936507936507936