In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/Social_Netw.csv')
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
df.isna().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
df.dtypes

Age                int64
EstimatedSalary    int64
Purchased          int64
dtype: object

In [14]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=2)
x_train

array([[    38,  61000],
       [    46,  22000],
       [    35,  57000],
       [    47, 113000],
       [    41,  63000],
       [    35,  50000],
       [    35,  22000],
       [    53,  34000],
       [    37,  74000],
       [    29,  47000],
       [    37,  70000],
       [    35,  73000],
       [    40,  59000],
       [    35,  79000],
       [    39,  71000],
       [    58, 144000],
       [    27,  20000],
       [    41,  80000],
       [    59,  29000],
       [    26,  52000],
       [    40,  75000],
       [    35,  38000],
       [    31,  71000],
       [    40,  72000],
       [    42,  65000],
       [    26,  32000],
       [    37, 146000],
       [    49,  65000],
       [    47, 105000],
       [    37,  79000],
       [    32,  18000],
       [    26,  35000],
       [    30, 116000],
       [    49,  89000],
       [    54,  26000],
       [    45,  22000],
       [    31,  34000],
       [    50,  88000],
       [    35,  20000],
       [    21,  88000],


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train


array([[ 0.02273414, -0.26389006],
       [ 0.79431698, -1.42026223],
       [-0.26660943, -0.38249233],
       [ 0.89076483,  1.2779395 ],
       [ 0.3120777 , -0.20458892],
       [-0.26660943, -0.59004631],
       [-0.26660943, -1.42026223],
       [ 1.46945196, -1.06445541],
       [-0.07371372,  0.12156733],
       [-0.84529656, -0.67899802],
       [-0.07371372,  0.00296506],
       [-0.26660943,  0.09191676],
       [ 0.21562985, -0.3231912 ],
       [-0.26660943,  0.26982017],
       [ 0.11918199,  0.03261563],
       [ 1.95169124,  2.19710712],
       [-1.03819227, -1.47956337],
       [ 0.3120777 ,  0.29947074],
       [ 2.04813909, -1.21270825],
       [-1.13464012, -0.53074518],
       [ 0.21562985,  0.1512179 ],
       [-0.26660943, -0.94585313],
       [-0.65240085,  0.03261563],
       [ 0.21562985,  0.06226619],
       [ 0.40852556, -0.14528779],
       [-1.13464012, -1.12375655],
       [-0.07371372,  2.25640826],
       [ 1.08366054, -0.14528779],
       [ 0.89076483,

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
model.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[69  8]
 [ 7 36]]


In [ ]:
print(accuracy_score(y_test,y_pred))

0.875
