In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/student_exam_data.csv')
df

Study Hours  Previous Exam Score  Pass/Fail
0       4.370861            81.889703          0
1       9.556429            72.165782          1
2       7.587945            58.571657          0
3       6.387926            88.827701          1
4       2.404168            81.083870          0
..           ...                  ...        ...
495     4.180170            45.494924          0
496     6.252905            95.038815          1
497     1.699612            48.209118          0
498     9.769553            97.014241          1
499     9.875897            66.760346          1

[500 rows x 3 columns]

In [3]:
df.head()

Study Hours  Previous Exam Score  Pass/Fail
0     4.370861            81.889703          0
1     9.556429            72.165782          1
2     7.587945            58.571657          0
3     6.387926            88.827701          1
4     2.404168            81.083870          0

In [5]:
df.tail()

Study Hours  Previous Exam Score  Pass/Fail
495     4.180170            45.494924          0
496     6.252905            95.038815          1
497     1.699612            48.209118          0
498     9.769553            97.014241          1
499     9.875897            66.760346          1

In [6]:
df.isna().sum()

Study Hours            0
Previous Exam Score    0
Pass/Fail              0
dtype: int64

In [7]:
df.dtypes

Study Hours            float64
Previous Exam Score    float64
Pass/Fail                int64
dtype: object

In [10]:
x=df.iloc[:,:-1].values
x

array([[ 4.37086107, 81.88970284],
       [ 9.55642876, 72.16578198],
       [ 7.58794548, 58.57165698],
       [ 6.38792636, 88.82770118],
       [ 2.40416776, 81.08387035],
       [ 2.40395068, 49.75701636],
       [ 1.52275251, 94.65563107],
       [ 8.79558531, 89.35223458],
       [ 6.41003511, 96.9879948 ],
       [ 7.3726532 , 83.5431705 ],
       [ 1.18526045, 76.80491176],
       [ 9.72918867, 65.09458218],
       [ 8.49198377, 95.963709  ],
       [ 2.911052  , 91.96383337],
       [ 2.6364247 , 42.71312021],
       [ 2.65064059, 41.58201847],
       [ 3.73818019, 62.58780201],
       [ 5.72280788, 88.63319985],
       [ 4.88750517, 99.23656776],
       [ 3.62106226, 49.02501347],
       [ 6.50667605, 75.64784292],
       [ 2.25544475, 62.8534514 ],
       [ 3.62930184, 98.19486387],
       [ 4.29725659, 90.52713539],
       [ 5.10462986, 90.29972228],
       [ 8.06658365, 68.12158959],
       [ 2.79706404, 64.88917014],
       [ 5.62810995, 56.40442432],
       [ 6.33173112,

In [11]:
y=df.iloc[:,-1].values
y

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=2)
x_train

array([[ 5.85408018, 84.89558142],
       [ 1.36655922, 65.13552697],
       [ 9.10376251, 70.45662272],
       [ 9.4305699 , 98.168226  ],
       [ 1.84583746, 60.74175961],
       [ 7.32235676, 92.60593821],
       [ 1.41805371, 91.88334258],
       [ 8.18465661, 53.75508371],
       [ 5.47523655, 52.68688042],
       [ 7.33292073, 61.74363395],
       [ 1.13910955, 53.93276171],
       [ 6.84967538, 83.3351541 ],
       [ 2.05360315, 55.47326113],
       [ 7.93870462, 93.80730459],
       [ 9.028419  , 52.0976392 ],
       [ 3.03846198, 71.47068337],
       [ 5.78219168, 49.15234257],
       [ 1.32348046, 94.50703368],
       [ 6.38792636, 88.82770118],
       [ 1.30949669, 53.71856833],
       [ 5.82197216, 54.2336075 ],
       [ 4.71355909, 91.34178809],
       [ 7.09807926, 50.40241572],
       [ 7.75553276, 45.96648357],
       [ 2.07634821, 48.32963036],
       [ 9.47318328, 64.04578365],
       [ 2.14354461, 41.08661103],
       [ 7.55394714, 74.24669828],
       [ 5.60883752,

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[5.40822878e-01, 7.45673685e-01],
       [3.61039604e-02, 4.12582794e-01],
       [9.06320034e-01, 5.02279334e-01],
       [9.43076602e-01, 9.69407736e-01],
       [9.00091779e-02, 3.38518024e-01],
       [7.05962377e-01, 8.75645474e-01],
       [4.18956314e-02, 8.63464838e-01],
       [8.02946671e-01, 2.20745165e-01],
       [4.98213708e-01, 2.02738697e-01],
       [7.07150525e-01, 3.55406399e-01],
       [1.05223189e-02, 2.23740244e-01],
       [6.52799119e-01, 7.19369905e-01],
       [1.13376929e-01, 2.49708104e-01],
       [7.75284043e-01, 8.95896643e-01],
       [8.97846024e-01, 1.92805987e-01],
       [2.24145634e-01, 5.19373132e-01],
       [5.32737460e-01, 1.43157770e-01],
       [3.12588213e-02, 9.07691822e-01],
       [6.00865442e-01, 8.11956563e-01],
       [2.96860430e-02, 2.20129633e-01],
       [5.37211635e-01, 2.28811535e-01],
       [4.12546581e-01, 8.54335973e-01],
       [6.80737515e-01, 1.64229978e-01],
       [7.54682401e-01, 8.94544452e-02],
       [1.159351

In [16]:
x_test

array([[ 0.5118778 ,  0.24419519],
       [ 0.89577982,  0.69074292],
       [ 0.08075298,  0.26606006],
       [ 0.73894836,  0.79791931],
       [ 0.24185371,  0.8403101 ],
       [ 0.29167755,  0.28670342],
       [ 0.95723216,  0.53109026],
       [ 0.70442887,  0.26429223],
       [ 0.63774675,  0.07520198],
       [ 0.84109306,  0.86869784],
       [ 0.5290392 ,  0.02041758],
       [ 0.17029273,  0.39243279],
       [ 0.6349248 ,  0.98664698],
       [ 0.21970394,  0.89429703],
       [ 0.3177579 ,  0.14681254],
       [ 0.89282516,  0.14500224],
       [ 0.61408765,  0.33978957],
       [ 0.37433727,  0.34860855],
       [ 0.35520797,  0.21604559],
       [ 0.69427465,  0.10219565],
       [ 0.11514927,  0.73533096],
       [ 0.47287359,  0.14251416],
       [ 0.7447157 ,  0.56526905],
       [ 0.01843334,  0.6553189 ],
       [ 0.54421779,  0.58552551],
       [ 0.01166738,  0.8958734 ],
       [ 0.43211058,  0.98741654],
       [ 0.50417356,  0.05672035],
       [ 0.06957663,

In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier(n_neighbors=7)
base=GaussianNB()
model=SVC()
lst=[knn,base,model]


In [20]:
for i in lst:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print('model is',i)
  print(y_pred)
  print('*'*100)
  print('Confusion Matrix:',confusion_matrix(y_test,y_pred))
  print('*'*100)
  print('accuracy score:',accuracy_score(y_test,y_pred))
  print('*'*100)
  print('classification_report:',classification_report(y_test,y_pred))

model is KNeighborsClassifier(n_neighbors=7)
[0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 1
 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 1 0 1 1 1 1
 0 1]
****************************************************************************************************
Confusion Matrix: [[93  1]
 [ 3 53]]
****************************************************************************************************
accuracy score: 0.9733333333333334
****************************************************************************************************
classification_report:               precision    recall  f1-score   support

           0       0.97      0.99      0.98        94
           1       0.98      0.95      0.96        56

    accuracy                           0.97       150
   macro avg       0.98      0.97